### ISSUE TITLE
Error: failed to generate container "..." spec: no command specified

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/krustlet#238]
I'm receiving this while trying to deploy Krustlet alongside GKE but I recall also receiving this error (ocassionally) when running with MicroK8s too.

Why does this error arise? Or, what does it mean? [So that I may debug the issue]

```bash
KUBECONFIG=${PWD}/kubeconfig-sa \
./krustlet-wasi \
--node-ip=${IP} \
--node-name=krustlet \
--pfx-password=password \
--pfx-path=./krustlet.pfx
```
> **NB** No errors are reported by the Krustlet.

Then:

```bash
kubectl apply --filename=https://raw.githubusercontent.com/deislabs/krustlet/master/demos/wasi/hello-world-rust/k8s.yaml
configmap/hello-world-wasi-rust created
pod/hello-world-wasi-rust created

kubectl get pods
NAME                    READY   STATUS                 RESTARTS   AGE
hello-world-wasi-rust   0/1     CreateContainerError   0          3s

kubectl describe pod/hello-world-wasi-rust
Name:         hello-world-wasi-rust
Namespace:    default
Priority:     0
Node:         gke-cluster-default-pool-9eff5757-jvh2/10.138.0.9
Start Time:   Wed, 06 May 2020 12:41:30 -0700
Labels:       <none>
Annotations:  Status:  Pending
IP:           10.36.0.22
IPs:
  IP:  10.36.0.22
Containers:
  hello-world-wasi-rust:
    Container ID:   
    Image:          webassembly.azurecr.io/hello-world-wasi-rust:v0.1.0
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:
      FOO:             bar
      POD_NAME:        hello-world-wasi-rust (v1:metadata.name)
      CONFIG_MAP_VAL:  <set to the key 'myval' of config map 'hello-world-wasi-rust'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fctpg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-fctpg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fctpg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     krustlet/arch=wasm32-wasi:NoExecute
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                                             Message
  ----     ------     ----               ----                                             -------
  Normal   Scheduled  15s                default-scheduler                                Successfully assigned default/hello-world-wasi-rust to gke-cluster-default-pool-9eff5757-jvh2
  Warning  Failed     15s                kubelet, gke-cluster-default-pool-9eff5757-jvh2  Error: failed to generate container "62327f82f3c82c7e0bfe609983e9c5e0b8141c96024c3020b3579e41fa9d41cb" spec: no command specified
  Normal   Pulled     14s (x2 over 15s)  kubelet, gke-cluster-default-pool-9eff5757-jvh2  Container image "webassembly.azurecr.io/hello-world-wasi-rust:v0.1.0" already present on machine
  Warning  Failed     14s                kubelet, gke-cluster-default-pool-9eff5757-jvh2  Error: failed to generate container "eeb455ae3b51961bca3b320d846b17fc3b9f21c19975d024579ae781a9d51595" spec: no command specified

**Comment by thomastaylor312** [comment]
So this happens when it gets scheduled to a normal node, my fixes in #232 should fix this with a node selector on the architecture.

For some reason, the tolerations don't always work

**Comment by DazWilkin** [comment]
Gosh you respond quickly! :-) Thank you.

I just deleted the GKE cluster but will try again tomorrow.

**Comment by DazWilkin** [comment]
Your suggestion worked, thank you!

I added the `nodeSelector` and the `network-unavailable` toleration:

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-wasi-rust
data:
  myval: "cool stuff"
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-wasi-rust
spec:
  containers:
    - name: hello-world-wasi-rust
      image: webassembly.azurecr.io/hello-world-wasi-rust:v0.1.0
      env:
        - name: FOO
          value: bar
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONFIG_MAP_VAL
          valueFrom:
            configMapKeyRef:
              key: myval
              name: hello-world-wasi-rust
  nodeSelector:
    kubernetes.io/arch: "wasm32-wasi"
  tolerations:
    - key: "krustlet/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
```
