### ISSUE TITLE
Document the need for image pull secrets

### ISSUE THREAD

**Issue by DerekStrickland** [deislabs/krustlet#327]
Working through the 1, 2, 3 first app tutorial, and discovered that I needed to create and add an image pull secret in order to pull from the azure registry I created.

Used this document to get passed the ImagePullBackoff. 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#:~:text=your%20service%20principal.-,Create%20an%20image%20pull%20secret,password%2C%20and%20the%20registry%20URL.

**Comment by bacongobbler** [comment]
Duplicate of #257?

**Comment by DerekStrickland** [comment]
> Duplicate of #257?

I don't think so.  What I am saying is that the documentation doesn't tell me that I need to  create an imagePullSecret and add it to the yaml. Once I followed the steps at the link I provide before to create the secret and then modified the yaml like so I stopped getting the authorization error message in the event stream, and started getting the error I documented in [issue 328](https://github.com/deislabs/krustlet/issues/328). From my perspective, that means I am able to pull the image.  So this issue, I hope, is just about documentation.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: krusty
spec:
  containers:
    - name: krusty
      image: consulcr.azurecr.io/krusty:v0.0.2
  **imagePullSecrets:
    - name: krusty-pull-secret**
  tolerations:
    - key: "krustlet/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
```
