### ISSUE TITLE
Cannot pull from Google Artifact Registry and no update on pull state

### ISSUE THREAD

**Issue by jiayihu** [deislabs/krustlet#469]
I have the hello-wasi example working if the image is pulled from GCP Registry but not from the new Artifact Registry. From logs, I can see that it panics here at line 152 with unexpected `None`:

https://github.com/deislabs/krustlet/blob/0a10d3f1e0c6ae9a2e00f61271db8c819321e465/crates/oci-distribution/src/client.rs#L143-L152

The pod YAML is just:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hello-wasi
spec:
  containers:
    - name: hello-wasi
      image: europe-west1-docker.pkg.dev/fedra-thesis/images/hello-wasi:latest
    # (working)  image: eu.gcr.io/fedra-thesis/hello-wasi:latest
  nodeSelector:
    kubernetes.io/arch: "wasm32-wasi"
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"
```

You can try it yourself to see that the pod remains in `Pending` status. I'll leave the image public, let me know if I delete it by mistake.  FYI `wasm-to-oci` is able to pull the image without issues.

Krustlet should also post updates about the image pull status, it wasn't intuitive debugging the cause of the eternal pending. The `describe` command only stated the following.

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  19m   default-scheduler  Successfully assigned default/hello-wasi to rasp-4
```

The usual kubelet is much richer with pull events as you know:

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  10s               default-scheduler  Successfully assigned default/hello-world to rasp-2
  Normal   Pulled     6s                kubelet            Successfully pulled image "hello-world" in 4.094783929s
  Normal   Pulling    5s (x2 over 10s)  kubelet            Pulling image "hello-world"
  Normal   Pulled     3s                kubelet            Successfully pulled image "hello-world" in 1.714372192s
  Normal   Created    3s (x2 over 6s)   kubelet            Created container hello-world
  Normal   Started    3s (x2 over 5s)   kubelet            Started container hello-world
  Warning  BackOff    1s (x2 over 2s)   kubelet            Back-off restarting failed container
```

I haven't tried yet with the latest commit in https://github.com/deislabs/krustlet/commit/a61a59091330dc600341deb81ace2d2520973775 but I don't think it solves the issue by looking at the diff.
