### ISSUE TITLE
[example - greet] No Headers returned in http Response 

### ISSUE THREAD

**Issue by david6983** [deislabs/krustlet#471]
Hello,

I tried to insert some headers in the response of the [greet](https://github.com/deislabs/krustlet/tree/master/demos/wascc/greet) example but when I look into my response headers with curl there are no headers added !

Here is the code:

```rust
extern crate wascc_actor as actor;

use std::collections::HashMap;

use actor::prelude::*;
use log::{info};

actor_handlers! { codec::http::OP_HANDLE_REQUEST => greet,
codec::core::OP_HEALTH_REQUEST => health }

pub fn greet(_r: codec::http::Request) -> HandlerResult<codec::http::Response> {
    let mut hm = HashMap::new();
    hm.insert("accept".to_string(), "application/json".to_string());
    hm.insert("dummy".to_string(), "value".to_string());

    let res = codec::http::Response {
        status_code: 200,
        status: "OK".to_string(),
        header: hm,
        body: b"Hello, World".to_vec(),
    };

    //println!(&format!("Received HTTP request: {:?}", &r));
    info!("res: {:?}", res);
    Ok(res)
}

pub fn health(_h: codec::core::HealthRequest) -> HandlerResult<()> {
    Ok(())
}
```

And here is the curl response:

```
$curl http://localhost:8080 -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 12
< date: Mon, 04 Jan 2021 13:53:16 GMT
<
* Connection #0 to host localhost left intact
Hello, World* Closing connection 0
```

**Comment by VishnuJin** [comment]
hi @david6983 
can you please let us know how you are running, like after building your source to wasm module, pushing it to the container registry and then using the newly created image in kubernetes yaml file.

**Comment by david6983** [comment]
here is the yaml file:

```
apiVersion: v1
kind: Pod
metadata:
  name: greet
  labels:
    app: greet
spec:
  containers:
    - image: registry.gitlab.com/MYREGISTRY/greet-wascc:v0.5
      imagePullPolicy: Always
      name: greet
      ports:
        - containerPort: 8080
          hostPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    beta.kubernetes.io/arch: wasm32-wascc
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wascc"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wascc"
      effect: "NoSchedule"
```

then I am running `kruslet-wascc` with kind on Mac OS X Catalina

```
krustlet-wascc --node-ip 192.168.0.48 --node-name krustlet --bootstrap-file=~/.krustlet/config/bootstrap.conf
```
