### ISSUE TITLE
Fix volume handling for 1.21

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#618]
Looks like k8s 1.21 added a new `projected` volume type that amalgamates all the functionality of the downward API stuff as well as secret/configmap volumes(see https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/). However, our current volume logic doesn't know how to handle it. It looks like the default service account token and certificate are automatically generated using this `projected` volume type like so:

```yaml
- name: kube-api-access-b59rx
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
```
